# Generated by Django 4.1.3 on 2022-11-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
