# Generated by Django 4.1.3 on 2022-11-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0002_studio_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='location',
        ),
    ]
