# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_alter_studio_latitude_alter_studio_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/studios/'),
        ),
    ]
