# Generated by Django 4.1.3 on 2022-11-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_tfcuser_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfcuser",
            name="card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.card",
            ),
        ),
    ]
