# Generated by Django 4.1.3 on 2022-11-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_tfcuser_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_number",
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name="tfcuser",
            name="card",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.card",
            ),
        ),
    ]
