# Generated by Django 4.1.3 on 2022-11-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0002_alter_class_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="is_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="Note: cancelling a class cancels all future sessions",
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="keywords",
            field=models.JSONField(blank=True, help_text="(JSON Field)", null=True),
        ),
        migrations.AlterField(
            model_name="class",
            name="session_length",
            field=models.DurationField(
                help_text="i.e., 00:01:00 for a one-hour session"
            ),
        ),
        migrations.AlterField(
            model_name="classsession",
            name="session_length",
            field=models.DurationField(
                help_text="i.e., 00:01:00 for a one-hour session"
            ),
        ),
    ]
