# Generated by Django 4.1.3 on 2022-11-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.PositiveIntegerField(help_text='Cost of Subscription in CAD'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='term_length',
            field=models.PositiveIntegerField(help_text='Length of a single term in months'),
        ),
    ]
