# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfcuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatars/'),
        ),
    ]
