# Generated by Django 4.1.3 on 2022-11-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_remove_studio_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
