# Generated by Django 4.1.3 on 2022-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_studio_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='studioimage',
            name='avatar',
        ),
        migrations.AddField(
            model_name='studioimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/studios/'),
        ),
    ]
