# Generated by Django 4.1.3 on 2022-12-06 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classes", "0003_alter_class_is_cancelled_alter_class_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="end_date",
            field=models.DateField(default=datetime.date(2023, 1, 6)),
        ),
    ]
