# Generated by Django 4.1.3 on 2022-12-07 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_class_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 1, 7)),
        ),
    ]
